import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../../helpers/colors";
import { LAYOUT } from "../../../helpers/layout";
import { SPACING, TYPOGRAPHY, VISUAL } from "../../../helpers/styleKit";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingBottom: 0,
  },
  headerContainer: {
    padding: 16,
    paddingBottom: 0,
    backgroundColor: COLORS.background,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  categoryFilterContainer: {
    marginBottom: 16,
  },
  categoryScrollView: {
    marginBottom: 8,
  },
  categoryScrollContent: {
    paddingHorizontal: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  categoryButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    marginLeft: 0,
    minWidth: 80,
    borderRadius: VISUAL.RADIUS.SMALL,
    backgroundColor: COLORS.backgroundDark,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  genreScrollView: {
    marginBottom: 8,
  },
  genreScrollContent: {
    paddingHorizontal: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  genreButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginLeft: 0,
    minWidth: 80,
    borderRadius: VISUAL.RADIUS.SMALL,
    backgroundColor: COLORS.backgroundDark,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    alignItems: "center",
    justifyContent: "center",
  },
  genreButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  headerAddButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  headerAddButtonText: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: "500",
  },
  listContentContainer: {
    paddingHorizontal: SPACING.MEDIUM,
    paddingBottom: 40,
    backgroundColor: COLORS.background,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  listContentContainerEmpty: {
    paddingHorizontal: SPACING.MEDIUM,
    paddingBottom: 40,
    backgroundColor: COLORS.background,
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  listStyle: {
    backgroundColor: COLORS.background,
  },
  listFooter: {
    height: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLighter,
    marginBottom: 16,
  },
  movieList: {
    paddingBottom: 16,
  },
  movieCard: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginBottom: 16,
    padding: 12,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  posterContainer: {
    marginRight: 12,
  },
  posterPlaceholder: {
    width: 80,
    height: 120,
    backgroundColor: COLORS.grayLighter,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  movieInfo: {
    flex: 1,
    justifyContent: "center",
  },
  movieTitle: {
    marginBottom: 4,
  },
  genreContainer: {
    flexDirection: "row",
    marginTop: 8,
  },
  genreTag: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginRight: 8,
    marginBottom: 8,
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  genreTagText: {
    color: COLORS.white,
    fontWeight: "bold",
    fontSize: 12,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  errorText: {
    textAlign: "center",
    marginBottom: 16,
  },
  retryButton: {
    minWidth: 120,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 40,
  },
  emptyText: {
    textAlign: "center",
    marginBottom: 16,
  },
  addMovieButton: {
    minWidth: 120,
  },
  mediaItem: {
    marginBottom: SPACING.MEDIUM,
    flexDirection: "column",
    alignItems: "center",
  },
  loadingMoreContainer: {
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  loadingMoreText: {
    marginLeft: 8,
    textAlign: "center",
  },
  columnWrapper: {
    justifyContent: "space-between",
    paddingHorizontal: SPACING.TINY,
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingOverlayContent: {
    backgroundColor: COLORS.backgroundDark,
    borderRadius: VISUAL.RADIUS.MEDIUM,
    padding: SPACING.LARGE,
    minWidth: width * 0.7,
    maxWidth: width * 0.8,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  loadingOverlayText: {
    marginTop: SPACING.MEDIUM,
    textAlign: "center",
    maxWidth: "90%",
  },
});
